### ISSUE TITLE
コマンドを整備する

### ISSUE THREAD

**Issue by wtnb75** [wtnb75/log2s3#5]
- コンテナ別/日付別にログを吐き出す(dockerのdaemon.json, rsyslogの設定)
- housekeeping (log2s3)

というだけなのだが、今はコマンドが分かれている。1発でできた方が楽だよね、と。

- 古くてでかいログを圧縮
    - filetree-compress --older 3d --newer 14d --bigger 100k --top /var/log/container --compress xz
- もっと古いログをS3に送る。圧縮してなかったやつも圧縮
    - s3-put --older 7d --newer 21d --compress xz --top /var/log/container --dotenv --bucket ${bucket_name} --prefix ${server_name}
- さらに古いログを削除する
    - filetree-delete --older 60d --top /var/log/container

**Comment by wtnb75** [comment]
ansible風にして1個1個実行していく感じにする？

```yaml
- name: compress old log
  filetree-compress:
    top: /var/log/container
    compress: xz
    older: 3d
    newer: 14d
    bigger: 100k
- name: put older log to s3
  s3-put:
    top: /var/log/container
    compress: xz
    older: 7d
    newer: 21d
- name: delete oldest logs
  filetree-delete:
    top: /var/log/container
    older: 60d
```
